const C=document.getElementById('g'),X=C.getContext('2d');let W,H,last=performance.now(),run=0,E=100,HP=100,K=0,S=0,phase='ARRIVAL',pt=0,fly=0,redir=0,dodge=0,dcd=0,combo=0,ct=0,spawned=0,escaping=0,escaped=0,alertT=0,shake=0,pulse=0,pres=0,mom=0;
let P={x:0,y:0},J={x:0,y:0},A=[],V=[],T=[];const enemy=(t,x,y,h)=>({t,x,y,h,max:h,slip:0,rec:0,m:100,tele:0,wind:0,cd:1,hold:0,broken:0});
function size(){let v=visualViewport||null,w=v?v.width:innerWidth,h=v?v.height:innerHeight,d=Math.max(1,Math.min(3,devicePixelRatio||1));C.width=w*d;C.height=h*d;C.style.width=w+'px';C.style.height=h+'px';X.setTransform(d,0,0,d,0,0);W=w;H=h}size();addEventListener('resize',size);addEventListener('orientationchange',()=>setTimeout(size,120));
function reset(){E=100;HP=100;K=S=0;phase='ARRIVAL';pt=0;fly=redir=dodge=dcd=combo=ct=spawned=escaping=escaped=alertT=shake=pulse=pres=mom=0;P.x=W*.5;P.y=H*.78;A=[enemy('GUNMAN',W*.48,H*.29,3),enemy('RUNNER',W*.72,H*.48,2)];V=[.16,.24,.31,.70,.79,.87].map((a,i)=>({x:W*a,y:H*(.30+(i%3)*.12),state:'DANGER',r:0,h:2,panic:10,ev:a<.5?W*.06:W*.94}));T=[];hud()}
function start(){document.getElementById('start').style.display='none';reset();run=1}document.getElementById('startBtn').addEventListener('click',start);window.startGame=start;
function alert(s,t=.9){let a=document.getElementById('alert');a.textContent=s;a.style.display='block';alertT=t}function gainM(v){mom=Math.min(100,mom+v);if(mom>=100){mom=0;E=Math.min(100,E+18);HP=Math.min(100,HP+6);S+=200;alert('HERO MOMENTUM +200')}}function gainP(v){pres=Math.min(100,pres+v)}function morale(e,v){e.m=Math.max(0,e.m-v);if(e.m<=0&&!e.broken){e.broken=1;e.rec=1.2;e.tele=e.wind=0;S+=75;T.push({x:e.x,y:e.y-32,s:'SHAKEN +75',t:1})}}
function near(){let n=null,b=1e9;for(let e of A){if(e.h<=0)continue;let d=Math.hypot(e.x-P.x,e.y-P.y),q=d;if(e.t==='RUNNER'&&escaping)q-=170;if(e.tele||e.wind)q-=100;if(V.some(v=>v.state==='DANGER'&&Math.hypot(v.x-e.x,v.y-e.y)<150))q-=120;if(q<b){b=q;n=e}}return[n,n?Math.hypot(n.x-P.x,n.y-P.y):1e9]}function spend(n){if(E<n)return 0;E-=n;return 1}function down(e){K++;S+=150;gainM(22);gainP(16);A.forEach(o=>{if(o!==e&&o.h>0&&Math.hypot(o.x-e.x,o.y-e.y)<200)morale(o,22)});T.push({x:e.x,y:e.y-28,s:'THREAT STOPPED +150',t:1})}
function attack(){let[e,d]=near();if(!e||d>(fly?165:125))return;if(fly&&!spend(4))return;combo=ct>0?Math.min(3,combo+1):1;ct=.85;let was=e.slip>0,dam=combo===3?2:1;if(was){dam++;e.slip=0;e.rec=.45;S+=85;gainM(16);gainP(18);morale(e,35)}e.h-=dam;S+=45*combo;pulse=.18;shake=combo===3?7:3;T.push({x:e.x,y:e.y-22,s:was?'CONTROL STRIKE -'+dam:'-'+dam,t:.75});if(e.h<=0)down(e)}
function slip(){let[e,d]=near();if(!e||d>235||!spend(12))return;let q=e.tele||e.wind;e.tele=e.wind=0;e.rec=.4;e.slip=e.t==='RUNNER'?3:1.8;if(q){S+=40;T.push({x:e.x,y:e.y-24,s:'CONTROL +40',t:.8})}}
function dodgeF(){if(dcd<=0&&!fly){dodge=.28;dcd=.8;let m=Math.hypot(J.x,J.y)||1,active=Math.abs(J.x)+Math.abs(J.y)>.15;P.x+=(active?J.x/m:0)*48;P.y+=(active?J.y/m:1)*48}}
document.getElementById('atk').onpointerdown=attack;document.getElementById('slip').onpointerdown=slip;document.getElementById('redir').onpointerdown=()=>{if(spend(16))redir=.8};document.getElementById('flight').onpointerdown=()=>{if(fly)fly=0;else if(spend(8))fly=1};document.getElementById('dodge').onpointerdown=dodgeF;
let stick=document.getElementById('stick'),nub=document.getElementById('nub'),sid=null;function js(e){let r=stick.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=Math.hypot(dx,dy),l=42;if(m>l){dx*=l/m;dy*=l/m}J.x=dx/l;J.y=dy/l;nub.style.transform=`translate(${dx}px,${dy}px)`}stick.onpointerdown=e=>{sid=e.pointerId;stick.setPointerCapture(sid);js(e)};stick.onpointermove=e=>{if(e.pointerId===sid)js(e)};stick.onpointerup=()=>{sid=null;J.x=J.y=0;nub.style.transform=''};
function setP(v){if(phase===v)return;phase=v;pt=0;alert(v.replace('_',' '),1.1)}function flow(dt){pt+=dt;if(phase==='ARRIVAL'&&pt>2)setP('ACTIVE_ROBBERY');if(phase==='ACTIVE_ROBBERY'&&!spawned&&(K>0||S>=240||pt>7)){spawned=1;A.push(enemy('BRAWLER',W*.18,H*.25,3));setP('REINFORCEMENTS')}if(spawned&&!escaping&&(K>=1||S>=360||pt>5)){escaping=1;setP('ESCAPE_ATTEMPT');alert('RUNNER MOVING TO GETAWAY',1.2)}let r=A.find(e=>e.t==='RUNNER'&&e.h>0);if(escaping&&!r&&A.some(e=>e.h>0))setP('RESOLUTION');if(A.length&&A.every(e=>e.h<=0))finish(1)}
function hud(){document.getElementById('hp').style.width=Math.max(0,HP)+'%';document.getElementById('en').style.width=Math.max(0,E)+'%';document.getElementById('kills').textContent=K;document.getElementById('civs').textContent=V.filter(v=>v.state==='SAFE').length;document.getElementById('state').textContent='ENCOUNTER: '+phase.replace('_',' ');document.getElementById('phaseLine').textContent={ARRIVAL:'Signo arriving on scene',ACTIVE_ROBBERY:'Gunman threatening civilians',REINFORCEMENTS:'Brawler reinforcement entered',ESCAPE_ATTEMPT:'Getaway attempt in progress',RESOLUTION:'Resolve remaining threats'}[phase];let r=A.find(e=>e.t==='RUNNER');document.getElementById('runner').textContent=!r||r.h<=0?'STOPPED':escaped?'ESCAPED':escaping?'ESCAPING':'AT SCENE';let o={ARRIVAL:'ASSESS THE SCENE',ACTIVE_ROBBERY:'PROTECT CIVILIANS / STOP GUNMAN',REINFORCEMENTS:'CONTROL THE ESCALATION',ESCAPE_ATTEMPT:'INTERCEPT RUNNER',RESOLUTION:'RESOLVE REMAINING THREATS'}[phase];document.getElementById('objective').textContent='OBJECTIVE: '+o}
function finish(ok){run=0;let safe=V.filter(v=>v.state==='SAFE').length,r=S>=1400?'S':S>=1000?'A':S>=650?'B':'C';document.getElementById('start').style.display='flex';document.querySelector('.card').innerHTML=ok?`<div class="logo">MISSION COMPLETE</div><div class="sub">HERO RATING</div><p style="font-size:42px;color:#f0b92f">${r}</p><p>Score: ${S}</p><p class="small">Civilians safe: ${safe}/6<br>Reserve: ${Math.round(E)}%</p><button id="again" class="startbtn">REPLAY</button>`:`<div class="logo">MISSION FAILED</div><p>${escaped?'The runner reached the getaway vehicle.':'Signo was overwhelmed.'}</p><button id="again" class="startbtn">RETRY</button>`;document.getElementById('again').onclick=start}
